### ISSUE TITLE
All files have no line breaks

### ISSUE THREAD

**Issue by TheTerrorByte** [sethwalker1/Ogar-Plus#2]
I wanna edit some of the code but the files dont have line breaks, and Im too lazy to paste it into a text box and copy it back to notepad, cuz it fixes it.

**Comment by Porama6400** [comment]
try Notepad++
it's good , and it have javascript support

**Comment by Creeperman8362** [comment]
Neither do the MD files, the ini, or botnames.txt.

**Comment by Porama6400** [comment]
Notepad++ support a lot of file type
try it , you will know!

**Comment by DaFudgeWizzad** [comment]
I use Notepad++

**Comment by DaFudgeWizzad** [comment]
I'm busy getting info on the new gamemode, but I would love it if you want to create a pull request.

**Comment by dazdylz** [comment]
Use atom.io or Brackets..


Notepad++ is shit for programming (my opion)

I also started with Notepad++ but I never want it back now.

**Comment by DaFudgeWizzad** [comment]
Thanks for the tip. If anyone can get the line breaks to work, I would be happy to merge a pull request.
